language: node_js
dist: xenial
addons:
  apt:
    packages:
      - libgif-dev
      - libpng16-dev
node_js:
    - 6
    - 8
    - 10
    - 11
before_install:
  - sudo apt autoremove
  - sudo apt-get remove libjpeg-turbo8-dev libjpeg9-dev+
script: npm run travis
sudo: false
